### PR TITLE
Fix running counts of labeled superpixels

### LINKED ISSUE #32: Labeled count not updating properly
If I'm overriding existing labels with a new label, the count for the existing label doesn't decrease as it should. Additionally, it takes 2 clicks to do this, when intuitively it should only take 1.

### PR DESCRIPTION
**Pull request by naglepuff**
Fixes #32 

Now, superpixel counts will change when re-labelling a superpixel. Additionally, Sets are used instead of arrays, and if two categories have the same name, they will both display in the running counts.

To reproduce the bug described in #32:
1. Open the initial labels view and label some superpixels with the initial category.
2. Create a new category
3. Label some of the previously labeled superpixels with the new category
4. Running count of the old category stays the same

To verify the fix in this PR, repeat the above steps, but in step 4, you should see the count update to reflect re-labeling.

While testing this PR, I discovered another issue where if two categories had the same name, they wouldn't show up separately in the running counts. Now, two categories can have the same name, and they will each have a line in the running counts section.

### CODE REVIEW

File: wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialLabels.vue [hunk 1]
```diff
@@ -174,10 +178,10 @@ export default Vue.extend({
                 if (categoryIndex !== 0) {
                     // For each non-default category, get all the labeled indices
                     // for this superpixel element.
-                    const labeledSuperpixels = [];
+                    const labeledSuperpixels = new Set();
```
Comment (naglepuff) [inline wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialLabels.vue:181]: Switched from arrays to Sets as the data structure. Our main operations here are adding a deleting, and it wouldn't make sense for a superpixel to be labeled twice, so I think this is the appropriate data structure.

File: wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialLabels.vue [hunk 2]
```diff
@@ -246,18 +251,23 @@ export default Vue.extend({
...
-                const newCategoryData = Object.assign({}, this.categories[this.categoryIndex]);
-                this.categories.splice(this.categoryIndex, 1, newCategoryData);
             }
+            if (newLabel === 0) {
+                currentCategoryIndices.delete(elementValueIndex);
+            } else if (oldLabel === 0) {
+                currentCategoryIndices.add(elementValueIndex);
+            } else {
+                this.categories[oldLabel - 1].indices[this.currentImageId].delete(elementValueIndex);
+                currentCategoryIndices.add(elementValueIndex);
```
Comment (naglepuff) [inline wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialLabels.vue:266]: This is the new case. If there's a superpixel that's labeled category X, and I want to label it category Y, this updates both counts.

File: wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialLabels.vue [hunk 3]
```diff
@@ -229,13 +233,14 @@ export default Vue.extend({
             const index = boundaries ? (event.index - event.index % 2) : event.index;
             const offset = boundaries ? 1 : 0;
             const data = this.overlayLayer.data();
-            // the +1 accounts for the default, reset to default if already labeled
-            const categoryIndex = data[index] === 0 ? this.categoryIndex + 1 : 0;
-            data[index] = data[index + offset] = categoryIndex;
+            const previousLabel = data[index];
+            // the +1 accounts for the default, reset to default if already labeled with the selected category
+            const newLabel = previousLabel !== this.categoryIndex + 1 ? this.categoryIndex + 1 : 0;
```
Comment (naglepuff) [inline wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialLabels.vue:238]: Previously if this superpixel was labeled and we clicked on it, we set it to default, regardless of what category is currently active for labeling. This was unintuitive to use, since you'd need 2 clicks to change an existing label.

**Comment by naglepuff** [comment]
@manthey I've added some review comments to explain the changes in more detail, and add some questions. Please take a look and let me know if you have any thoughts

File: wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialLabels.vue [hunk 4]
```diff
@@ -49,13 +49,17 @@ export default Vue.extend({
...
         labeledSuperpixelCounts() {
             const counts = {};
-            _.forEach(this.categories, (categoryAndIndices) => {
+            _.forEach(this.categories, (categoryAndIndices, index) => {
                 const label = categoryAndIndices.category.label;
-                counts[label] = 0;
+                const key = `${index}_${label}`;
+                counts[key] = {
+                    count: 0,
+                    label
```
[the remark this answers is not in the document]
Comment (manthey) [reply wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialLabels.vue:57]: I think we better prevent two categories with the same name.

File: wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialLabels.vue (hunk 3 above)
Comment (manthey) [reply wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialLabels.vue:238]: Good.

**Review by manthey — APPROVED** [review]
Aside from preventing category name duplication, this looks good.

**Comment by naglepuff** [comment]
@manthey see 7314ca2 for some validation logic and UI that prevents multiple category names. If you think the commit is too large for this PR, I can move it to a new branch and get this merged.

**Comment by manthey** [comment]
> @manthey see [7314ca2](https://github.com/DigitalSlideArchive/wsi-superpixel-guided-labeling/commit/7314ca2a53e1e5a964abc1bf5ea748ae408a327e) for some validation logic and UI that prevents multiple category names. If you think the commit is too large for this PR, I can move it to a new branch and get this merged.

Looks reasonable to me.
